db:
  driver:
  url:
  username:
  password:

project:
  name:
  buildTool:
  mainPackage:
  utilPackage:
  modulePackage:

export:
  dir:
  models:
    - model: po
#    - model: dao
#    - model: daoXml
    - model: mapper
    - model: mapperXml
    - model: controller
    - model: service

tables:
  - tableName:
    javaType:
